export const ADMIN_TRANSLATIONS = {
  es: {
    crud: { actions: 'Acciones', edit: 'Editar {name}', delete: 'Eliminar {name}', search: 'Buscar…', searchIn: 'Buscar en {name}', empty: 'Sin registros', noMatches: 'No hay coincidencias con tu búsqueda.', createFirst: 'Crear el primero', reviewForm: 'Revisa el formulario', invalidFields: 'Hay campos con información inválida.', updated: 'Registro actualizado', saved: 'Los cambios se guardaron correctamente.', created: 'Registro creado', available: 'El nuevo elemento ya está disponible.', saveError: 'No se pudo guardar', deleted: 'Registro eliminado', removed: 'El elemento se retiró del sistema.', deleteError: 'No se pudo eliminar', editTitle: 'Editar {name}', newTitle: 'Nuevo {name}', editDescription: 'Modifica los campos y guarda los cambios.', newDescription: 'Completa la información del nuevo registro.', cancel: 'Cancelar', save: 'Guardar cambios', create: 'Crear', confirmDelete: 'Confirmar eliminación', deletePrompt: '¿Seguro que deseas eliminar {name}? Esta acción no se puede deshacer.', defaultRecord: 'este registro', yesDelete: 'Sí, eliminar' },
    adminAvailability: { title: 'Disponibilidad de fechas', description: 'Consulta la ocupación horaria de cada espacio antes de aprobar nuevas reservas.', space: 'Espacio', selectSpace: 'Selecciona un espacio', date: 'Fecha', choose: 'Elige un espacio y una fecha para ver su ocupación.', legend: 'Leyenda de disponibilidad', free: 'Libre', occupied: 'Ocupado', reservations: 'Reservas registradas', empty: 'Sin reservas para esta fecha.' },
    adminReports: { title: 'Reportes', description: 'Indicadores de uso, ingresos y participación comunitaria.', export: 'Exportar CSV', bookings: 'Reservas', income: 'Ingresos', users: 'Usuarios', usage: 'Uso por espacio', chart: 'Gráfico de barras horizontales con el uso de cada espacio', reservationTotal: '{count} reservas', total: 'Total', csvSpace: 'Espacio', csvBookings: 'Reservas' },
    errors: { forbiddenTitle: 'Acceso restringido', forbiddenDescription: 'Tu cuenta no tiene los permisos necesarios para ver esta sección. Si crees que es un error, contacta a la administración del centro.', notFoundDescription: 'La página que buscas no existe o fue movida.', home: 'Volver al inicio' },
  },
  en: {
    crud: { actions: 'Actions', edit: 'Edit {name}', delete: 'Delete {name}', search: 'Search…', searchIn: 'Search {name}', empty: 'No records', noMatches: 'No matches for your search.', createFirst: 'Create the first one', reviewForm: 'Check the form', invalidFields: 'Some fields contain invalid information.', updated: 'Record updated', saved: 'Changes saved successfully.', created: 'Record created', available: 'The new item is now available.', saveError: 'Could not save', deleted: 'Record deleted', removed: 'The item was removed from the system.', deleteError: 'Could not delete', editTitle: 'Edit {name}', newTitle: 'New {name}', editDescription: 'Edit the fields and save your changes.', newDescription: 'Enter the new record information.', cancel: 'Cancel', save: 'Save changes', create: 'Create', confirmDelete: 'Confirm deletion', deletePrompt: 'Are you sure you want to delete {name}? This action cannot be undone.', defaultRecord: 'this record', yesDelete: 'Yes, delete' },
    adminAvailability: { title: 'Date availability', description: 'Check each space’s hourly occupancy before approving new bookings.', space: 'Space', selectSpace: 'Select a space', date: 'Date', choose: 'Choose a space and date to view its occupancy.', legend: 'Availability legend', free: 'Available', occupied: 'Occupied', reservations: 'Recorded bookings', empty: 'No bookings for this date.' },
    adminReports: { title: 'Reports', description: 'Usage, income, and community participation metrics.', export: 'Export CSV', bookings: 'Bookings', income: 'Income', users: 'Users', usage: 'Usage by space', chart: 'Horizontal bar chart showing usage by space', reservationTotal: '{count} bookings', total: 'Total', csvSpace: 'Space', csvBookings: 'Bookings' },
    errors: { forbiddenTitle: 'Access restricted', forbiddenDescription: 'Your account does not have permission to view this section. If you think this is a mistake, contact the center administration.', notFoundDescription: 'The page you are looking for does not exist or has moved.', home: 'Back to home' },
  },
  zh: {
    crud: { actions: '操作', edit: '編輯 {name}', delete: '刪除 {name}', search: '搜尋…', searchIn: '搜尋「{name}」', empty: '沒有記錄', noMatches: '找不到符合搜尋條件的項目。', createFirst: '建立第一筆', reviewForm: '請檢查表單', invalidFields: '部分欄位的資料無效。', updated: '記錄已更新', saved: '變更已成功儲存。', created: '記錄已建立', available: '新項目現已可用。', saveError: '無法儲存', deleted: '記錄已刪除', removed: '項目已從系統移除。', deleteError: '無法刪除', editTitle: '編輯 {name}', newTitle: '新增 {name}', editDescription: '修改欄位並儲存變更。', newDescription: '輸入新記錄的資料。', cancel: '取消', save: '儲存變更', create: '建立', confirmDelete: '確認刪除', deletePrompt: '確定要刪除「{name}」嗎？此操作無法復原。', defaultRecord: '此記錄', yesDelete: '是，刪除' },
    adminAvailability: { title: '日期可用狀況', description: '核准新預約前，請先查看各場地的每小時使用情況。', space: '場地', selectSpace: '選擇場地', date: '日期', choose: '選擇場地與日期以查看使用情況。', legend: '可用狀況圖例', free: '可用', occupied: '已占用', reservations: '已登記預約', empty: '此日期沒有預約。' },
    adminReports: { title: '報表', description: '場地使用、收入與社群參與指標。', export: '匯出 CSV', bookings: '預約', income: '收入', users: '使用者', usage: '各場地使用情況', chart: '各場地使用情況橫向長條圖', reservationTotal: '{count} 筆預約', total: '總計', csvSpace: '場地', csvBookings: '預約' },
    errors: { forbiddenTitle: '存取受限', forbiddenDescription: '你的帳戶沒有查看此區域的權限。如認為這是錯誤，請聯絡中心管理單位。', notFoundDescription: '找不到此頁面，或頁面已移動。', home: '返回首頁' },
  },
};
