export const MORE_TRANSLATIONS = {
  es: {
    myBookings: { eyebrow: 'Mi cuenta', title: 'Mis reservas', description: 'Consulta el estado de tus solicitudes de espacio.', empty: 'Aún no tienes reservas', emptyDescription: 'Cuando solicites un espacio, aparecerá aquí con su estado de aprobación.', cancel: 'Cancelar', canceled: 'Reserva cancelada', canceledDescription: 'Tu reserva fue cancelada correctamente.', cancelError: 'No se pudo cancelar' },
    spaceDetail: { loading: 'Cargando espacio…', back: 'Volver a espacios', capacity: 'Capacidad', people: '{count} personas', location: 'Ubicación', rate: 'Tarifa', hour: '/ hora', accessible: 'Accesible para personas con discapacidad', available: 'Disponible', unavailable: 'No disponible', todayBookings: 'Reservas de hoy', freeDay: 'Día libre', noBookings: 'No hay reservas registradas para hoy en este espacio.', updated: 'Última actualización: {date}', interested: '¿Te interesa este espacio?', requestDescription: 'Envía tu solicitud de reserva y el equipo administrativo la revisará en un plazo de 48 horas.', request: 'Solicitar reserva' },
    newsDetail: { loading: 'Cargando noticia…', back: 'Volver a noticias', schoolMemory: 'Memoria de la Escuela Primo Vargas', generations: 'Una memoria que pasa de generación en generación', birth: 'Nacimiento', death: 'Defunción' },
    adminNav: { brand: 'Admin Centro', subtitle: 'Panel de gestión', close: 'Cerrar menú lateral', navigation: 'Navegación del panel', collapse: 'Colapsar', expand: 'Expandir', sections: { summary: 'Resumen', operation: 'Operación', catalog: 'Catálogo', administration: 'Administración' }, items: { dashboard: 'Dashboard', reservations: 'Reservas', availability: 'Disponibilidad', tickets: 'Boletos', spaces: 'Espacios', events: 'Eventos', content: 'Contenido histórico', users: 'Usuarios', reports: 'Reportes' } },
  },
  en: {
    myBookings: { eyebrow: 'My account', title: 'My bookings', description: 'Check the status of your space requests.', empty: 'You have no bookings yet', emptyDescription: 'When you request a space, it will appear here with its approval status.', cancel: 'Cancel', canceled: 'Booking canceled', canceledDescription: 'Your booking was canceled successfully.', cancelError: 'Could not cancel the booking' },
    spaceDetail: { loading: 'Loading space…', back: 'Back to spaces', capacity: 'Capacity', people: '{count} people', location: 'Location', rate: 'Rate', hour: '/ hour', accessible: 'Accessible for people with disabilities', available: 'Available', unavailable: 'Unavailable', todayBookings: 'Today’s bookings', freeDay: 'Available today', noBookings: 'No bookings are recorded for this space today.', updated: 'Last updated: {date}', interested: 'Interested in this space?', requestDescription: 'Submit a booking request and the administrative team will review it within 48 hours.', request: 'Request a booking' },
    newsDetail: { loading: 'Loading news…', back: 'Back to news', schoolMemory: 'Primo Vargas School memories', generations: 'A memory passed down through generations', birth: 'Birth', death: 'Death' },
    adminNav: { brand: 'Center Admin', subtitle: 'Management panel', close: 'Close side menu', navigation: 'Panel navigation', collapse: 'Collapse', expand: 'Expand', sections: { summary: 'Overview', operation: 'Operations', catalog: 'Catalog', administration: 'Administration' }, items: { dashboard: 'Dashboard', reservations: 'Bookings', availability: 'Availability', tickets: 'Tickets', spaces: 'Spaces', events: 'Events', content: 'Historical content', users: 'Users', reports: 'Reports' } },
  },
  zh: {
    myBookings: { eyebrow: '我的帳戶', title: '我的預約', description: '查看場地申請狀態。', empty: '目前沒有預約', emptyDescription: '提出場地申請後，其核准狀態會顯示在這裡。', cancel: '取消', canceled: '預約已取消', canceledDescription: '預約已成功取消。', cancelError: '無法取消預約' },
    spaceDetail: { loading: '正在載入場地…', back: '返回場地列表', capacity: '容納人數', people: '{count} 人', location: '地點', rate: '費率', hour: '/ 小時', accessible: '方便身心障礙者使用', available: '可用', unavailable: '暫不可用', todayBookings: '今日預約', freeDay: '今日空檔', noBookings: '此場地今天沒有預約紀錄。', updated: '最後更新：{date}', interested: '對這個場地有興趣嗎？', requestDescription: '提交預約申請後，行政團隊會在 48 小時內審核。', request: '申請預約' },
    newsDetail: { loading: '正在載入新聞…', back: '返回新聞', schoolMemory: '普里莫·巴爾加斯學校記憶', generations: '代代相傳的共同記憶', birth: '出生', death: '逝世' },
    adminNav: { brand: '中心管理', subtitle: '管理面板', close: '關閉側邊選單', navigation: '面板導覽', collapse: '收合', expand: '展開', sections: { summary: '總覽', operation: '營運', catalog: '目錄', administration: '管理' }, items: { dashboard: '儀表板', reservations: '預約', availability: '場地狀況', tickets: '門票', spaces: '場地', events: '活動', content: '歷史內容', users: '使用者', reports: '報表' } },
  },
};
