export const TRANSLATIONS = {
  es: {
    common: { home: 'Inicio', calendar: 'Calendario', spaces: 'Espacios', tickets: 'Boletos', arts: 'Teatro · Baile · Canto', gallery: 'Galería Ferrocarril', history: 'Historia', news: 'Noticias', explore: 'Explorar', close: 'Cerrar', login: 'Ingresar', signup: 'Registrarse', logout: 'Cerrar sesión', myBookings: 'Mis reservas', panel: 'Panel', adminPanel: 'Panel administrativo', changeLanguage: 'Cambiar idioma a', mainNavigation: 'Navegación principal', publicSections: 'Secciones públicas', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú', accessibility: 'Accesibilidad', assistant: 'Asistente Cultural' },
    home: { eyebrow: 'Orotina · Alajuela · Costa Rica', description: 'Un espacio vivo donde la memoria del Ferrocarril al Pacífico se encuentra con el teatro, la danza, el canto y las artes visuales del Pacífico Central.', program: 'Ver programación', book: 'Reservar un espacio', spacesCount: 'Espacios', activities: 'Actividades/año', heritage: 'Patrimonio vivo', quickAccess: 'Accesos rápidos', agenda: 'Agenda', upcoming: 'Próximos eventos', upcomingDescription: 'Teatro, danza, música y exposiciones en el corazón del Pacífico Central.', fullCalendar: 'Ver calendario completo', ai: 'Inteligencia artificial', recommended: 'Recomendado para ti', recommendedDescription: 'Nuestro asistente analiza el catálogo cultural y tu historial de participación para sugerirte actividades afines.', current: 'Actualidad', centerNews: 'Noticias del centro', allNews: 'Todas las noticias', legacy: 'La memoria del riel, viva en Orotina', legacyDescription: 'Recorre la historia del Ferrocarril al Pacífico, conoce las y los artistas del cantón y descubre por qué este centro lleva el nombre del escritor orotinense Luis Ferrero Acosta.', learnHistory: 'Conocer la historia', viewGallery: 'Ver galería', access: { calendar: ['Calendario', 'Programación cultural'], spaces: ['Espacios', 'Salas y galerías'], tickets: ['Boletos', 'Entradas en línea'], gallery: ['Galería Ferrocarril', 'Memoria del tren'] }, disciplines: { theater: ['Teatro', 'Temporadas profesionales y comunitarias.'], dance: ['Baile', 'Danza folclórica y contemporánea.'], singing: ['Canto', 'Coro infantil y formación vocal.'], visual: ['Artes visuales', 'Exposiciones y residencias.'] } },
    accessibility: { preferences: 'Preferencias de acceso', saved: 'Ajustes guardados en este dispositivo.', textSize: 'Tamaño del texto', reset: 'Restablecer accesibilidad', contrast: 'Alto contraste', underline: 'Enlaces subrayados', motion: 'Reducir movimiento', feedback: 'Alertas visuales', on: 'Activado', off: 'Desactivado' },
    weather: { title: 'Clima en Orotina', unavailable: 'Clima no disponible en este momento.', retry: 'Reintentar', humidity: 'humedad', wind: 'viento', forecast: 'Pronóstico extendido', days: '{count} días', today: 'Hoy', rain: 'lluvia', viewDetails: 'Ver detalles del pronóstico', outdoor: 'Eventos al aire libre', source: 'Datos reales de Open-Meteo' },
  },
  en: {
    common: { home: 'Home', calendar: 'Calendar', spaces: 'Spaces', tickets: 'Tickets', arts: 'Theater · Dance · Song', gallery: 'Railway Gallery', history: 'History', news: 'News', explore: 'Explore', close: 'Close', login: 'Log in', signup: 'Sign up', logout: 'Log out', myBookings: 'My bookings', panel: 'Panel', adminPanel: 'Admin panel', changeLanguage: 'Change language to', mainNavigation: 'Main navigation', publicSections: 'Public sections', openMenu: 'Open menu', closeMenu: 'Close menu', accessibility: 'Accessibility', assistant: 'Cultural Assistant' },
    home: { eyebrow: 'Orotina · Alajuela · Costa Rica', description: 'A living space where the memory of the Pacific Railway meets theater, dance, song, and visual arts from the Central Pacific.', program: 'View program', book: 'Book a space', spacesCount: 'Spaces', activities: 'Activities/year', heritage: 'Living heritage', quickAccess: 'Quick access', agenda: 'Agenda', upcoming: 'Upcoming events', upcomingDescription: 'Theater, dance, music, and exhibitions in the heart of the Central Pacific.', fullCalendar: 'View full calendar', ai: 'Artificial intelligence', recommended: 'Recommended for you', recommendedDescription: 'Our assistant analyzes the cultural catalog and your participation history to suggest activities you may enjoy.', current: 'Latest', centerNews: 'Center news', allNews: 'All news', legacy: 'The memory of the railway, alive in Orotina', legacyDescription: 'Explore the history of the Pacific Railway, meet local artists, and discover why this center bears the name of Orotina writer Luis Ferrero Acosta.', learnHistory: 'Learn our history', viewGallery: 'View gallery', access: { calendar: ['Calendar', 'Cultural program'], spaces: ['Spaces', 'Rooms and galleries'], tickets: ['Tickets', 'Online tickets'], gallery: ['Railway Gallery', 'Memory of the railway'] }, disciplines: { theater: ['Theater', 'Professional and community seasons.'], dance: ['Dance', 'Folk and contemporary dance.'], singing: ['Song', "Children's choir and vocal training."], visual: ['Visual arts', 'Exhibitions and residencies.'] } },
    accessibility: { preferences: 'Accessibility preferences', saved: 'Settings saved on this device.', textSize: 'Text size', reset: 'Reset accessibility', contrast: 'High contrast', underline: 'Underlined links', motion: 'Reduce motion', feedback: 'Visual alerts', on: 'On', off: 'Off' },
    weather: { title: 'Weather in Orotina', unavailable: 'Weather is unavailable right now.', retry: 'Retry', humidity: 'humidity', wind: 'wind', forecast: 'Extended forecast', days: '{count} days', today: 'Today', rain: 'rain', viewDetails: 'View forecast details', outdoor: 'Outdoor events', source: 'Live data from Open-Meteo' },
  },
  zh: {
    common: { home: '首頁', calendar: '日曆', spaces: '空間', tickets: '門票', arts: '戲劇 · 舞蹈 · 歌唱', gallery: '鐵路畫廊', history: '歷史', news: '新聞', explore: '探索', close: '關閉', login: '登入', signup: '註冊', logout: '登出', myBookings: '我的預約', panel: '控制台', adminPanel: '管理面板', changeLanguage: '切換語言至', mainNavigation: '主要導航', publicSections: '公開區域', openMenu: '開啟選單', closeMenu: '關閉選單', accessibility: '無障礙', assistant: '文化助理' },
    home: { eyebrow: '奧羅蒂納 · 阿拉胡埃拉 · 哥斯大黎加', description: '一個充滿活力的空間，讓太平洋鐵路的記憶與中太平洋地區的戲劇、舞蹈、歌唱和視覺藝術相遇。', program: '查看節目', book: '預約空間', spacesCount: '空間', activities: '每年活動', heritage: '活的遺產', quickAccess: '快速入口', agenda: '活動日程', upcoming: '近期活動', upcomingDescription: '中太平洋地區中心的戲劇、舞蹈、音樂和展覽。', fullCalendar: '查看完整日曆', ai: '人工智慧', recommended: '為你推薦', recommendedDescription: '我們的助理會分析文化目錄和你的參與歷史，推薦適合你的活動。', current: '最新消息', centerNews: '中心新聞', allNews: '所有新聞', legacy: '鐵路記憶，在奧羅蒂納延續', legacyDescription: '探索太平洋鐵路的歷史，認識本地藝術家，了解中心以奧羅蒂納作家 Luis Ferrero Acosta 命名的原因。', learnHistory: '了解歷史', viewGallery: '查看畫廊', access: { calendar: ['日曆', '文化節目'], spaces: ['空間', '展廳與畫廊'], tickets: ['門票', '線上購票'], gallery: ['鐵路畫廊', '鐵路記憶'] }, disciplines: { theater: ['戲劇', '專業與社區演出。'], dance: ['舞蹈', '民俗與現代舞。'], singing: ['歌唱', '兒童合唱與聲樂培訓。'], visual: ['視覺藝術', '展覽與駐地計畫。'] } },
    accessibility: { preferences: '無障礙偏好設定', saved: '設定已儲存在此裝置。', textSize: '文字大小', reset: '重設無障礙設定', contrast: '高對比', underline: '連結加底線', motion: '減少動態效果', feedback: '視覺提示', on: '已開啟', off: '已關閉' },
    weather: { title: '奧羅蒂納天氣', unavailable: '目前無法取得天氣資料。', retry: '重試', humidity: '濕度', wind: '風速', forecast: '延伸預報', days: '{count} 天', today: '今天', rain: '降雨', viewDetails: '查看預報詳情', outdoor: '戶外活動', source: 'Open-Meteo 即時資料' },
  },
};

export function getTranslation(language, key) {
  return key.split('.').reduce((value, part) => value?.[part], TRANSLATIONS[language])
    ?? key.split('.').reduce((value, part) => value?.[part], TRANSLATIONS.es)
    ?? key;
}