export const PATHS = {
  home: '/',
  calendario: '/calendario',
  espacios: '/espacios',
  espacioDetalle: (id = ':id') => `/espacios/${id}`,
  reservas: '/reservas',
  misReservas: '/mis-reservas',
  boletos: '/boletos',
  historia: '/historia',
  galeria: '/galeria',
  artes: '/artes',
  noticias: '/noticias',
  noticiaDetalle: (id = ':id') => `/noticias/${id}`,
  login: '/login',
  registro: '/registro',
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    espacios: '/admin/espacios',
    reservas: '/admin/reservas',
    disponibilidad: '/admin/disponibilidad',
    eventos: '/admin/eventos',
    boletos: '/admin/boletos',
    usuarios: '/admin/usuarios',
    contenido: '/admin/contenido',
    reportes: '/admin/reportes',
  },
};